// <auto-generated />
using System;
using GroceristLibrary.DB;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace GroceristLibrary.Migrations
{
    [DbContext(typeof(GroceristContext))]
    [Migration("20180922181600_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.3-rtm-32065")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("GroceristLibrary.DB.Entities.UserList", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.ToTable("UserList");
                });

            modelBuilder.Entity("GroceristLibrary.DB.Entities.UserListItem", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name");

                    b.Property<string>("Notes");

                    b.Property<long?>("UserListId");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.HasIndex("UserListId");

                    b.ToTable("UserListItem");
                });

            modelBuilder.Entity("GroceristLibrary.DB.Entities.UserListItem", b =>
                {
                    b.HasOne("GroceristLibrary.DB.Entities.UserList")
                        .WithMany("Items")
                        .HasForeignKey("UserListId");
                });
#pragma warning restore 612, 618
        }
    }
}
